#SystemMail Config
SENDMAIL="no"
SENDMAILONERROR="no"
MAILFROM="system-scripts@$HOST"
MAILRECIP="alerts@$HOST"
MAILSUB="System-Scripts: $PROG"
MAILHEADER="The $PROG script has been ran on $HOST"
MAILMESS1=""
MAILMESS2=""
MAILMESS3="Either no errors were reported or you have not enabled error reporting"
MAILFOOTER="Please check the $LOGFILE for more information"
STARTSUBJECT="$HOST - System Startup"
STOPSUBJECT="$HOST - System Shutdown"
STARTBODY="This is an automated message to notify you that $HOST started successfully on `date +"%a %m/%d/%y"` at `date +"%H:%M"`"
STOPBODY="This is an automated message to notify you that $HOST is shutting down on `date +"%a %m/%d/%y"` at `date +"%H:%M"`"

#Other sending configurations
SENDXMPP="no"
SENDTWIT="no"
SENDSMS="no"
XMPP="sendxmpp all@broadcast.your.server -f /root/.sendxmpprc"
EMAIL="root@$HOST"
TWEETYSENDER="mysecureemail@$HOST"
TWITTER="tweet@tweetymail.com"
GVOICE="gvoice send_sms yournumber"
